set(SIMDPP_VERSION 2.0-rc2)
set(SIMDPP_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/deps/simdpp")

if(NOT EXISTS ${SIMDPP_INCLUDE_DIR})
    message(STATUS "Downloading simdpp v${SIMDPP_VERSION}...")
    set(tmp_dir "${CMAKE_CURRENT_SOURCE_DIR}/deps/tmp")
    set(tar_file "${tmp_dir}/simdpp.tar.gz")
    download("https://github.com/p12tic/libsimdpp/archive/v${SIMDPP_VERSION}.tar.gz" ${tar_file})

    execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf ${tar_file} WORKING_DIRECTORY ${tmp_dir})
    file(REMOVE ${tar_file})
    set(ex_dir ${tmp_dir}/libsimdpp-${SIMDPP_VERSION})

    if(NOT EXISTS ${ex_dir})
        message(FATAL_ERROR "Error downloading simdpp v${SIMDPP_VERSION}")
    else()
        file(MAKE_DIRECTORY ${SIMDPP_INCLUDE_DIR})
        file(RENAME ${ex_dir}/simdpp ${SIMDPP_INCLUDE_DIR}/simdpp)
        file(REMOVE_RECURSE ${tmp_dir})
    endif()
endif()
